<template>
  <svg
    viewBox="0 0 55 55"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <circle
      cx="27.5"
      cy="27.5"
      r="27.5"
      fill="url(#paint0_linear_321_513)"
    />
    <circle
      cx="36"
      cy="36"
      r="16"
      fill="url(#paint1_linear_321_513)"
    />
    <defs>
      <linearGradient
        id="paint0_linear_321_513"
        x1="27.5"
        y1="0"
        x2="27.5"
        y2="55"
        gradientUnits="userSpaceOnUse"
      >
        <stop stop-color="#FF0000" />
        <stop
          offset="1"
          stop-color="#FFBFBF"
          stop-opacity="0.44"
        />
      </linearGradient>
      <linearGradient
        id="paint1_linear_321_513"
        x1="36"
        y1="20"
        x2="23.5"
        y2="42.5"
        gradientUnits="userSpaceOnUse"
      >
        <stop stop-color="#F368CC" />
        <stop
          offset="1"
          stop-color="#FF00B8"
          stop-opacity="0"
        />
      </linearGradient>
    </defs>
  </svg>
</template>
